### ISSUE TITLE
Black screen in Enlighten2 plugin window during protein prep

### ISSUE THREAD

**Issue by artemisDiscovery** [vanderkamp/enlighten2#5]
Hi, I have installed latest version of Enlighten2 using Pymol 2.3.4 under macOS 11.2.3

The latest version of Docker is installed (3.2.2) and Docker desktop is running.
 
In Pymol I loaded a PDB file (6WHA A chain) which has a ligand (U0G). 

I opened the Enlighten2 plug-in, kept the current Pymol object as selection, created a working directory, assigned system name ('complex'), assigned ligand name as in the PDB file (U0G), set ligand charge to 1, kept Run equilibration unchecked, and selected Run PREP.

A window labeled 'Prep' appears, with completely black content. There is no apparent system activity, and the docker container is not started.

This results in the creation of a file 'params' in the working directory with content {"propka": {"ph": 7.0}, "tleap": {"solvent_radius": 20, "include": ["."]}}, and a PDB file with ATOM and CONECT records.

Thanks,

Randy Zauhar
artemisdiscovery@me.com, r.zauhar@usciences.edu

**Comment by artemisDiscovery** [comment]
Just an update to this - I assumed that the Docker container was included with the plugin distribution, which seemed like a cool idea - but I see no evidence of that in the download.

**Comment by artemisDiscovery** [comment]
Another update - 

I grabbed your container, and started it. I also put a print into docker_process.py so I could catch what command was being issued, and in fact Pymol did not seem to run the command. I could however run it manually from the command line, here is an example - 

docker run --name iknckjrele --rm -v "/Users/zauhar/SARCourse/complex5":/tmp -u 501:20 kzinovjev/enlighten2 /bin/bash -lc "prep.py complex 6WHAA.pdb U0G 1 params"

This did create an output directory in /Users/zauhar/SARCourse/complex5, and looking at the antechamber output, it looks like it expected hydrogens to be attached, and of course they are not present in the PDB file. I don't use AMBER regularly, so there may be other tools that need to be run first.

So there are two issues : 
 1) Pymol does not seem to be running the docker command, as the output directory is not created; however, I can run the command manually and it does cause the directory to be created and output to appear

2) However, unless I am misunderstanding, I can't use a 'raw ' structure, and I was hoping to have protein preparation, etc working from inside pymol.

Appreciate any advice you can offer. 

Randy

**Comment by kzinovjev** [comment]
Hi Randy!

There indeed seems to be two separate issues. 

Regarding the PyMOL/Docker behavior, it seems to be specific to all MacOS 11+ versions. Looks like the docker calls are not executed from within PyMOL. This also explains why the enlighten2 image was not fetched - it should have happened when you run the system preparation for the first time. That's why the image is not included in the distribution - there is no need for that because it is fetched automatically from Docker Hub. We are currently looking into the issue.

Regarding the structure used, you are right, the hydrogens must be placed in PyMOL before running Enlighten2, but only for the ligand - the hydrogens on the protein will be placed automatically. The reason for that is that generic hydrogen placement algorithms often fail at getting the protonation well (confusing single/double bonds etc.). So it is better for the user to provide the protonation manually. Luckily, it is very easy to do with PyMOL (see the part regarding the `h_add` command in the [tutorial](https://enlighten2.github.io/tutorial1/).
Could you please try that on a Windows or Linux machine, just to make sure that this issue is unrelated to the first one?

**Comment by artemisDiscovery** [comment]
Hi Marc,

I was afraid of that. I accidentally upgraded to OS11 and lots of things broke. 

I see a few discussion threads about python subprocesses not working in OS11 , but for me the subprocess module works in python 3.8 in the terminal, so maybe depends on it being launched from inside a running app (like maybe some new Apple security bullshit?)

(BTW, thanks, now I understand about the ligand VS protein hydrogens, same situation in VMD. )

Sorry I don't have any windows machines, and my linux hardware is in a rack,  but will check in a VM if I have  chance . Also I have a colleague who relies heavily on AMBER, I will let him know about Enlighten, maybe he can try out, I will let you know.

In any event I will not be able to use Enlighten if not functioning in OS 11 - I am teaching a course next week (remote teaching) where I planned to have the students use Pymol, and I discovered that various plug-ins are broken by OS 11 - I was excited to discover Enlighten, but it will not work on my machine, and I know some students have OS 11 installed.

I may have to back up to VMD and NAMD (VMD still works under 11).

Thanks for your fast response. I think using a container with the plugin is a brilliant idea.  I will look forward to trying Enlighten once this issue is fixed. 

All the best,
Randy

**Comment by kzinovjev** [comment]
The issue was with how MacOS manages the environment variables - the $PATH that is available within PyMOL is not the same as the "global" one and does not include /usr/local/bin, which is the default location for docker executable. I have just pushed a fix to the plugin repository. @artemisDiscovery, could you please remove the plugin, download the new one (using the download button on top of the [project page](https://enlighten2.github.io/) and check if it works now?

**Comment by artemisDiscovery** [comment]
Kiril, sorry I missed this, and thank you for looking into this issue. I will check it out.

**Comment by artemisDiscovery** [comment]
Hey that fixed it!

My example still fails, but it's AMBER errors, no longer a black dialog.

One trivial issue - I had to run

docker image rm --force kzinovjev/enlighten2

to remove the old image. 

Thanks very much!

**Comment by kzinovjev** [comment]
Great! It is weird that you had to refetch the image because only the PyMOL plugin was changed. Anyway, glad it worked!
